// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/maisiq/go-words-jar/internal/transport/http/middleware.SecretService -o secret_service_mock.go -n SecretServiceMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// SecretServiceMock implements mm_middleware.SecretService
type SecretServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcPublicKeys          func(ctx context.Context) (m1 map[string]any, err error)
	funcPublicKeysOrigin    string
	inspectFuncPublicKeys   func(ctx context.Context)
	afterPublicKeysCounter  uint64
	beforePublicKeysCounter uint64
	PublicKeysMock          mSecretServiceMockPublicKeys
}

// NewSecretServiceMock returns a mock for mm_middleware.SecretService
func NewSecretServiceMock(t minimock.Tester) *SecretServiceMock {
	m := &SecretServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.PublicKeysMock = mSecretServiceMockPublicKeys{mock: m}
	m.PublicKeysMock.callArgs = []*SecretServiceMockPublicKeysParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mSecretServiceMockPublicKeys struct {
	optional           bool
	mock               *SecretServiceMock
	defaultExpectation *SecretServiceMockPublicKeysExpectation
	expectations       []*SecretServiceMockPublicKeysExpectation

	callArgs []*SecretServiceMockPublicKeysParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SecretServiceMockPublicKeysExpectation specifies expectation struct of the SecretService.PublicKeys
type SecretServiceMockPublicKeysExpectation struct {
	mock               *SecretServiceMock
	params             *SecretServiceMockPublicKeysParams
	paramPtrs          *SecretServiceMockPublicKeysParamPtrs
	expectationOrigins SecretServiceMockPublicKeysExpectationOrigins
	results            *SecretServiceMockPublicKeysResults
	returnOrigin       string
	Counter            uint64
}

// SecretServiceMockPublicKeysParams contains parameters of the SecretService.PublicKeys
type SecretServiceMockPublicKeysParams struct {
	ctx context.Context
}

// SecretServiceMockPublicKeysParamPtrs contains pointers to parameters of the SecretService.PublicKeys
type SecretServiceMockPublicKeysParamPtrs struct {
	ctx *context.Context
}

// SecretServiceMockPublicKeysResults contains results of the SecretService.PublicKeys
type SecretServiceMockPublicKeysResults struct {
	m1  map[string]any
	err error
}

// SecretServiceMockPublicKeysOrigins contains origins of expectations of the SecretService.PublicKeys
type SecretServiceMockPublicKeysExpectationOrigins struct {
	origin    string
	originCtx string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmPublicKeys *mSecretServiceMockPublicKeys) Optional() *mSecretServiceMockPublicKeys {
	mmPublicKeys.optional = true
	return mmPublicKeys
}

// Expect sets up expected params for SecretService.PublicKeys
func (mmPublicKeys *mSecretServiceMockPublicKeys) Expect(ctx context.Context) *mSecretServiceMockPublicKeys {
	if mmPublicKeys.mock.funcPublicKeys != nil {
		mmPublicKeys.mock.t.Fatalf("SecretServiceMock.PublicKeys mock is already set by Set")
	}

	if mmPublicKeys.defaultExpectation == nil {
		mmPublicKeys.defaultExpectation = &SecretServiceMockPublicKeysExpectation{}
	}

	if mmPublicKeys.defaultExpectation.paramPtrs != nil {
		mmPublicKeys.mock.t.Fatalf("SecretServiceMock.PublicKeys mock is already set by ExpectParams functions")
	}

	mmPublicKeys.defaultExpectation.params = &SecretServiceMockPublicKeysParams{ctx}
	mmPublicKeys.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmPublicKeys.expectations {
		if minimock.Equal(e.params, mmPublicKeys.defaultExpectation.params) {
			mmPublicKeys.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmPublicKeys.defaultExpectation.params)
		}
	}

	return mmPublicKeys
}

// ExpectCtxParam1 sets up expected param ctx for SecretService.PublicKeys
func (mmPublicKeys *mSecretServiceMockPublicKeys) ExpectCtxParam1(ctx context.Context) *mSecretServiceMockPublicKeys {
	if mmPublicKeys.mock.funcPublicKeys != nil {
		mmPublicKeys.mock.t.Fatalf("SecretServiceMock.PublicKeys mock is already set by Set")
	}

	if mmPublicKeys.defaultExpectation == nil {
		mmPublicKeys.defaultExpectation = &SecretServiceMockPublicKeysExpectation{}
	}

	if mmPublicKeys.defaultExpectation.params != nil {
		mmPublicKeys.mock.t.Fatalf("SecretServiceMock.PublicKeys mock is already set by Expect")
	}

	if mmPublicKeys.defaultExpectation.paramPtrs == nil {
		mmPublicKeys.defaultExpectation.paramPtrs = &SecretServiceMockPublicKeysParamPtrs{}
	}
	mmPublicKeys.defaultExpectation.paramPtrs.ctx = &ctx
	mmPublicKeys.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmPublicKeys
}

// Inspect accepts an inspector function that has same arguments as the SecretService.PublicKeys
func (mmPublicKeys *mSecretServiceMockPublicKeys) Inspect(f func(ctx context.Context)) *mSecretServiceMockPublicKeys {
	if mmPublicKeys.mock.inspectFuncPublicKeys != nil {
		mmPublicKeys.mock.t.Fatalf("Inspect function is already set for SecretServiceMock.PublicKeys")
	}

	mmPublicKeys.mock.inspectFuncPublicKeys = f

	return mmPublicKeys
}

// Return sets up results that will be returned by SecretService.PublicKeys
func (mmPublicKeys *mSecretServiceMockPublicKeys) Return(m1 map[string]any, err error) *SecretServiceMock {
	if mmPublicKeys.mock.funcPublicKeys != nil {
		mmPublicKeys.mock.t.Fatalf("SecretServiceMock.PublicKeys mock is already set by Set")
	}

	if mmPublicKeys.defaultExpectation == nil {
		mmPublicKeys.defaultExpectation = &SecretServiceMockPublicKeysExpectation{mock: mmPublicKeys.mock}
	}
	mmPublicKeys.defaultExpectation.results = &SecretServiceMockPublicKeysResults{m1, err}
	mmPublicKeys.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmPublicKeys.mock
}

// Set uses given function f to mock the SecretService.PublicKeys method
func (mmPublicKeys *mSecretServiceMockPublicKeys) Set(f func(ctx context.Context) (m1 map[string]any, err error)) *SecretServiceMock {
	if mmPublicKeys.defaultExpectation != nil {
		mmPublicKeys.mock.t.Fatalf("Default expectation is already set for the SecretService.PublicKeys method")
	}

	if len(mmPublicKeys.expectations) > 0 {
		mmPublicKeys.mock.t.Fatalf("Some expectations are already set for the SecretService.PublicKeys method")
	}

	mmPublicKeys.mock.funcPublicKeys = f
	mmPublicKeys.mock.funcPublicKeysOrigin = minimock.CallerInfo(1)
	return mmPublicKeys.mock
}

// When sets expectation for the SecretService.PublicKeys which will trigger the result defined by the following
// Then helper
func (mmPublicKeys *mSecretServiceMockPublicKeys) When(ctx context.Context) *SecretServiceMockPublicKeysExpectation {
	if mmPublicKeys.mock.funcPublicKeys != nil {
		mmPublicKeys.mock.t.Fatalf("SecretServiceMock.PublicKeys mock is already set by Set")
	}

	expectation := &SecretServiceMockPublicKeysExpectation{
		mock:               mmPublicKeys.mock,
		params:             &SecretServiceMockPublicKeysParams{ctx},
		expectationOrigins: SecretServiceMockPublicKeysExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmPublicKeys.expectations = append(mmPublicKeys.expectations, expectation)
	return expectation
}

// Then sets up SecretService.PublicKeys return parameters for the expectation previously defined by the When method
func (e *SecretServiceMockPublicKeysExpectation) Then(m1 map[string]any, err error) *SecretServiceMock {
	e.results = &SecretServiceMockPublicKeysResults{m1, err}
	return e.mock
}

// Times sets number of times SecretService.PublicKeys should be invoked
func (mmPublicKeys *mSecretServiceMockPublicKeys) Times(n uint64) *mSecretServiceMockPublicKeys {
	if n == 0 {
		mmPublicKeys.mock.t.Fatalf("Times of SecretServiceMock.PublicKeys mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmPublicKeys.expectedInvocations, n)
	mmPublicKeys.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmPublicKeys
}

func (mmPublicKeys *mSecretServiceMockPublicKeys) invocationsDone() bool {
	if len(mmPublicKeys.expectations) == 0 && mmPublicKeys.defaultExpectation == nil && mmPublicKeys.mock.funcPublicKeys == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmPublicKeys.mock.afterPublicKeysCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmPublicKeys.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// PublicKeys implements mm_middleware.SecretService
func (mmPublicKeys *SecretServiceMock) PublicKeys(ctx context.Context) (m1 map[string]any, err error) {
	mm_atomic.AddUint64(&mmPublicKeys.beforePublicKeysCounter, 1)
	defer mm_atomic.AddUint64(&mmPublicKeys.afterPublicKeysCounter, 1)

	mmPublicKeys.t.Helper()

	if mmPublicKeys.inspectFuncPublicKeys != nil {
		mmPublicKeys.inspectFuncPublicKeys(ctx)
	}

	mm_params := SecretServiceMockPublicKeysParams{ctx}

	// Record call args
	mmPublicKeys.PublicKeysMock.mutex.Lock()
	mmPublicKeys.PublicKeysMock.callArgs = append(mmPublicKeys.PublicKeysMock.callArgs, &mm_params)
	mmPublicKeys.PublicKeysMock.mutex.Unlock()

	for _, e := range mmPublicKeys.PublicKeysMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.m1, e.results.err
		}
	}

	if mmPublicKeys.PublicKeysMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmPublicKeys.PublicKeysMock.defaultExpectation.Counter, 1)
		mm_want := mmPublicKeys.PublicKeysMock.defaultExpectation.params
		mm_want_ptrs := mmPublicKeys.PublicKeysMock.defaultExpectation.paramPtrs

		mm_got := SecretServiceMockPublicKeysParams{ctx}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmPublicKeys.t.Errorf("SecretServiceMock.PublicKeys got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmPublicKeys.PublicKeysMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmPublicKeys.t.Errorf("SecretServiceMock.PublicKeys got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmPublicKeys.PublicKeysMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmPublicKeys.PublicKeysMock.defaultExpectation.results
		if mm_results == nil {
			mmPublicKeys.t.Fatal("No results are set for the SecretServiceMock.PublicKeys")
		}
		return (*mm_results).m1, (*mm_results).err
	}
	if mmPublicKeys.funcPublicKeys != nil {
		return mmPublicKeys.funcPublicKeys(ctx)
	}
	mmPublicKeys.t.Fatalf("Unexpected call to SecretServiceMock.PublicKeys. %v", ctx)
	return
}

// PublicKeysAfterCounter returns a count of finished SecretServiceMock.PublicKeys invocations
func (mmPublicKeys *SecretServiceMock) PublicKeysAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPublicKeys.afterPublicKeysCounter)
}

// PublicKeysBeforeCounter returns a count of SecretServiceMock.PublicKeys invocations
func (mmPublicKeys *SecretServiceMock) PublicKeysBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPublicKeys.beforePublicKeysCounter)
}

// Calls returns a list of arguments used in each call to SecretServiceMock.PublicKeys.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmPublicKeys *mSecretServiceMockPublicKeys) Calls() []*SecretServiceMockPublicKeysParams {
	mmPublicKeys.mutex.RLock()

	argCopy := make([]*SecretServiceMockPublicKeysParams, len(mmPublicKeys.callArgs))
	copy(argCopy, mmPublicKeys.callArgs)

	mmPublicKeys.mutex.RUnlock()

	return argCopy
}

// MinimockPublicKeysDone returns true if the count of the PublicKeys invocations corresponds
// the number of defined expectations
func (m *SecretServiceMock) MinimockPublicKeysDone() bool {
	if m.PublicKeysMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.PublicKeysMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.PublicKeysMock.invocationsDone()
}

// MinimockPublicKeysInspect logs each unmet expectation
func (m *SecretServiceMock) MinimockPublicKeysInspect() {
	for _, e := range m.PublicKeysMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SecretServiceMock.PublicKeys at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterPublicKeysCounter := mm_atomic.LoadUint64(&m.afterPublicKeysCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.PublicKeysMock.defaultExpectation != nil && afterPublicKeysCounter < 1 {
		if m.PublicKeysMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SecretServiceMock.PublicKeys at\n%s", m.PublicKeysMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SecretServiceMock.PublicKeys at\n%s with params: %#v", m.PublicKeysMock.defaultExpectation.expectationOrigins.origin, *m.PublicKeysMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPublicKeys != nil && afterPublicKeysCounter < 1 {
		m.t.Errorf("Expected call to SecretServiceMock.PublicKeys at\n%s", m.funcPublicKeysOrigin)
	}

	if !m.PublicKeysMock.invocationsDone() && afterPublicKeysCounter > 0 {
		m.t.Errorf("Expected %d calls to SecretServiceMock.PublicKeys at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.PublicKeysMock.expectedInvocations), m.PublicKeysMock.expectedInvocationsOrigin, afterPublicKeysCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *SecretServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockPublicKeysInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *SecretServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *SecretServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockPublicKeysDone()
}
